## Exercici 1
Crea una funció que donat un Array d’una dimensió, et faci un resum estadístic bàsic de les dades.
Si detecta que l’array té més d’una dimensió, ha de mostrar un missatge d’error.

In [14]:
import numpy as np
from numpy import random

def resumenEstadistico(array):
    if array.ndim > 1:
        return 'Error: el array tienes más de una dimensión'
    else:
        valorMax = np.max(array)
        valorMin = np.min(array)
        media = np.mean(array)
        mediana = np.median(array)
        desviacionEstandar = np.std(array)
        return 'Maximo ' + str(valorMax), 'Minimo ' + str(valorMin), 'Media ' + str(media), 'Mediana ' + str(mediana), 'Desviación estandar  ' + str(desviacionEstandar)

array1d = np.array([1,3,4,1,11,89,0,38,9])  
resumenEstadistico(array1d)

('Maximo 89',
 'Minimo 0',
 'Media 17.333333333333332',
 'Mediana 4.0',
 'Desviación estandar  27.668674625929512')

## Exercici 2
Crea una funció que et generi un quadrat NxN de nombres aleatoris entre el 0 i el 100.

In [3]:
from numpy import random

def quadratNN(num):
    nnArray = random.randint(100, size=(num, num))
    return(nnArray)
    
print(quadratNN(4))


[[49 16  8 15]
 [41 71 93 20]
 [ 5 98 18 91]
 [ 4 47 44 64]]


## Exercici 3
Crea una funció que donada una taula de dues dimensions (NxM), et calculi els totals per fila i els totals per columna.

In [8]:
import numpy as np

def totalFilasColumnas(taula):
    sumaColumna = taula.sum(axis=0)
    sumaFila =taula.sum(axis=1)
    return 'Suma de las filas: ' + str(sumaFila), 'Suma de las columnas' + str(sumaColumna)

nmArray = random.randint(100, size=(5, 3)) 
print(totalFilasColumnas(nmArray))


[[ 2 78  5]
 [19 26 37]
 [26 15 49]
 [40 43 23]
 [51 85 40]]
('Suma de las filas: [ 85  82  90 106 176]', 'Suma de las columnas[138 247 154]')


## Exercici 4
Implementa manualment una funció que calculi el coeficient de correlació. Informa-te'n sobre els seus usos i interpretació.

In [9]:
import numpy as np

def coeficientCorrelacio (arr1,arr2):
    #NUMERADOR
    mediaArr1 =arr1.mean()
    mediaArr2 = arr2.mean()

    distanciaArr1 = arr1 - mediaArr1
    distanciaArr2 = arr2 - mediaArr2
    
    #suma de los productos
    productos = np.prod([distanciaArr1, distanciaArr2], axis = 0)
    numerador= np.sum(productos)
    
    #DENOMINAR
    sumaCuadrados= (np.sum(distanciaArr1**2)*(np.sum(distanciaArr2**2)))
    denominador = np.sqrt(sumaCuadrados)

    #CORRELACION
    correlacion = numerador/denominador
    
    return correlacion


ventaHelados = np.array([3,6,9])#arr1
tempF =np.array([70,75,80])#arr2

coeficientCorrelacio (ventaHelados,tempF)


1.0